const users = [
  {
    id: "410544b2-4001-4271-9855-fec4b6a6442a",
    username: "CaptainUnderpants",
    email: "pantsless@heromail.com",
    password: "wedgiePower123",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    is_active: true,
    last_login: null,
    user_role: "user",
    email_verified: true,
  },
  {
    id: "7b8e8f6d-9c0d-4b1a-8f9e-3f9e7b8d9c0d",
    username: "PizzaWhisperer",
    email: "extra.cheese@slicehaven.com",
    password: "iLoveCrust2024",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    is_active: true,
    last_login: null,
    user_role: "user",
    email_verified: false,
  },
  {
    id: "1a2b3c4d-5e6f-7890-9abc-123456789012",
    username: "NapQueen",
    email: "zzz@snoozeville.net",
    password: "pillowFort99",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    is_active: false,
    last_login: null,
    user_role: "user",
    email_verified: true,
  },
  {
    id: "9a8b7c6d-5e4f-3210-1234-f1e2d3c4b5a6",
    username: "DancingAvocado",
    email: "guac.star@fruitgroove.com",
    password: "toastMyBread42",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    is_active: true,
    last_login: null,
    user_role: "user",
    email_verified: false,
  },
  {
    id: "2a3b4c5d-6e7f-8a9b-0c1d-a2b3c4d5e6f7",
    username: "CoffeeWizard",
    email: "espresso.patronum@beanmagic.org",
    password: "caffeineOverload!",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    is_active: true,
    last_login: null,
    user_role: "user",
    email_verified: true,
  },
];

export { users };
